apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/component: web-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/component: web-server
  ports:
    - name: http
      port: 80
      targetPort: 80
